<<<<<<< HEAD
=======
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        php:
          version: 7.3.11
          apt_packages:
            - libyaml
          pecl_extensions:
            - yaml
          ini:
            'date.timezone': 'UTC'

      dependencies:
        before:
          - cd /home/scrutinizer/build
          - composer install --no-interaction
          - ./vendor/bin/codecept build
          - echo -e 'opcache.enable_cli=1' >> /home/scrutinizer/.phpenv/versions/7.3.11/etc/php.ini
          - echo -e 'apc.enabled=1'        >> /home/scrutinizer/.phpenv/versions/7.3.11/etc/php.ini
          - echo -e 'apc.enable_cli=1'     >> /home/scrutinizer/.phpenv/versions/7.3.11/etc/php.ini

      tests:
        override:
          -
            command: phpcs-run
          -
            command: ./vendor/bin/phpstan analyse -l max -c phpstan.neon src -v
          -
            command: './vendor/bin/codecept run --coverage-xml'
            coverage:
              file: './tests/_output/coverage.xml'
              format: 'clover'
          - php-scrutinizer-run --enable-security-analysis
    tests: true

>>>>>>> Trying 7.3.0 for scrutinizer
filter:
  paths:
    - 'src/*'
tools:
  external_code_coverage: true
  php_code_coverage: true
  php_code_sniffer:
    config:
      standard: PSR12
    filter:
      paths: ['src']
  php_sim: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  php_cpd: true
