build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        php:
          version: 7.3.0
          ini:
            'date.timezone': 'UTC'

      dependencies:
        before:
          - cd /home/scrutinizer/build
          - composer install --no-interaction
          - ./vendor/bin/codecept build
          - echo -e 'opcache.enable_cli=1' >> /home/scrutinizer/.phpenv/versions/7.3.0/etc/php.ini
          - echo -e 'apc.enabled=1'        >> /home/scrutinizer/.phpenv/versions/7.3.0/etc/php.ini
          - echo -e 'apc.enable_cli=1'     >> /home/scrutinizer/.phpenv/versions/7.3.0/etc/php.ini
          -
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: true
          -
            command: './vendor/bin/codecept run --coverage-xml'
            coverage:
              file: './tests/_output/coverage.xml'
              format: 'clover'
          - php-scrutinizer-run --enable-security-analysis
    tests: true

filter:
  paths:
    - 'src/*'
  excluded_paths:
    - 'bin/*'
    - 'config/*'
    - 'docs/*'
    - 'public/*'
    - 'resources/*'
    - 'tests/*'
    - 'vendor/*'

build_failure_conditions:
  # No classes/methods with a rating of D or worse
  - 'elements.rating(<= C).exists'
  # No new classes/methods with a rating of D or worse allowed
  - 'elements.rating(<= C).new.exists'

  # No coding style issues allowed - Removing it for now until we fix index.php
  - 'issues.label("coding-style").exists'
  # No new coding style issues allowed
  - 'issues.label("coding-style").new.exists'

  # More than 5 new coding style issues.
  - 'issues.label("coding-style").new.count > 5'
  # New issues of major or higher severity
  - 'issues.severity(>= MAJOR).new.exists'

  # Code Quality Rating drops below 6
  - 'project.metric("scrutinizer.quality", < 8)'
  # Code Coverage drops below 60%
  - 'project.metric("scrutinizer.test_coverage", < 0.80)'

  # Code Coverage decreased from previous inspection by more than 10%
  - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'

tools:
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths:
        - 'src'
  php_loc:
    enabled: true
    excluded_dirs:
      - 'bin'
      - 'config'
      - 'docs'
      - 'public'
      - 'resources'
      - 'tests'
      - 'vendor'
  php_cpd:
    enabled: true
    excluded_dirs:
      - 'bin'
      - 'config'
      - 'docs'
      - 'public'
      - 'resources'
      - 'tests'
      - 'vendor'

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      general:
        linefeed_character: newline
      before_parentheses:
        function_declaration: false
        closure_definition: false
        function_call: false
        if: true
        for: true
        while: true
        switch: true
        catch: true
        array_initializer: false
      around_operators:
        assignment: true
        logical: true
        equality: true
        relational: true
        bitwise: true
        additive: true
        multiplicative: true
        shift: true
        unary_additive: false
        concatenation: false
        negation: false
      before_left_brace:
        class: true
        function: true
        if: true
        else: true
        for: true
        while: true
        do: true
        switch: true
        try: true
        catch: true
        finally: true
      before_keywords:
        else: true
        while: true
        catch: true
        finally: true
      within:
        brackets: false
        array_initializer: false
        grouping: false
        function_call: false
        function_declaration: false
        if: false
        for: false
        while: false
        switch: false
        catch: false
        type_cast: false
      ternary_operator:
        before_condition: true
        after_condition: true
        before_alternative: true
        after_alternative: true
        in_short_version: false
      other:
        before_comma: false
        after_comma: true
        before_semicolon: false
        after_semicolon: true
        after_type_cast: true
    braces:
      classes_functions:
        class: undefined
        function: undefined
        closure: undefined
      if:
        opening: undefined
        always: true
        else_on_new_line: false
      for:
        opening: undefined
        always: true
      while:
        opening: undefined
        always: true
      do_while:
        opening: undefined
        always: true
        while_on_new_line: false
      switch:
        opening: undefined
      try:
        opening: undefined
        catch_on_new_line: false
        finally_on_new_line: false
    upper_lower_casing:
      keywords:
        general: lower
      constants:
        true_false_null: lower

